Marginals Layout added
TEDxNITRourkela/website-v2 pull request #12
Opened 2021-11-08 19:21 UTC by sambit-sankalp

### Your checklist for this pull request
🚨Please review the [guidelines for contributing](../CONTRIBUTING.md) to this repository.

- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). Don't request your default branch!
- [x] Make sure you are making a pull request against the **default branch** (left side). Also you should start *your branch* off *default branch*.
- [x] Check the commit's or even all commits' message styles matches our requested structure.
- [x] Check your code additions will fail neither code linting checks nor unit test.
- [x] I have added necessary documentation (if appropriate)

### Description
Fixes #3 
> Navbar added
>Footer added

❤️Thank you!

### Post merge checklist
- [x] Follow steps from the [guidelines for contributing](../CONTRIBUTING.md) to this repository.
- [x] If you are a new contributor, ping in the thread and one of the maintainers will add you to all-contributors list.

2021-11-09 05:01 UTC, riteshsp2000 requested changes

2021-11-11 10:29 UTC, riteshsp2000 commented
<p float="left">

  <img src="https://user-images.githubusercontent.com/56112399/141281671-9a611413-fb83-47ed-b5e2-da368a9bae59.png" width="300" />
  <img src="https://user-images.githubusercontent.com/56112399/141281683-25b6ffaa-8862-4b91-86da-ccd8689dbe9e.png" width="300" /> 

</p>


As you can see above, there are a few issues

- The container margin is too much... at max it should be 95%. quite a lot of space is being wasted.
- The navitems aren't centered. 
- Replace the arrow with a cross

2021-11-11 10:32 UTC, sambit-sankalp commented
> <img alt="" width="300" src="https://user-images.githubusercontent.com/56112399/141281671-9a611413-fb83-47ed-b5e2-da368a9bae59.png"> <img alt="" width="300" src="https://user-images.githubusercontent.com/56112399/141281683-25b6ffaa-8862-4b91-86da-ccd8689dbe9e.png">
> 
> @sambit-sankalp As you can see above, there are a few issues
> 
> * The container margin is too much... at max it should be 95%. quite a lot of space is being wasted.
> * The navitems aren't centered.
> * Replace the arrow with a cross
> * Also, add privacy policy and terms of service in the footer.(no need to link them, just add the text for now)

okay bhaiya

2021-11-11 15:56 UTC, riteshsp2000 approved these changes

2021-11-11 15:56 UTC, merged